# Generated by Django 5.2.3 on 2025-07-28 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('submitted_on', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('zalo', models.CharField(max_length=20)),
                ('tiktok_url', models.URLField()),
                ('tiktok_id', models.CharField(max_length=100)),
                ('followers', models.CharField(max_length=20)),
                ('gmv', models.CharField(max_length=20)),
                ('channel_identifier', models.CharField(max_length=100)),
                ('appropriate_channel_topic', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('brand_approval', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('kol_koc_approval_time', models.DateField()),
                ('number_tracking', models.CharField(max_length=20)),
                ('koc_confirmed_by_nova', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kols', to='myapp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255)),
                ('creator_id', models.CharField(max_length=100)),
                ('about_video', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=100)),
                ('upload_time', models.CharField(max_length=50)),
                ('view', models.IntegerField()),
                ('like', models.IntegerField()),
                ('share', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('product_linked', models.URLField()),
                ('new_followers', models.IntegerField()),
                ('product_impressions', models.IntegerField()),
                ('product_entries', models.IntegerField()),
                ('gmv', models.IntegerField()),
                ('ctr', models.IntegerField()),
                ('revenue_from_videos', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_tracking', to='myapp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('tracking_url', models.URLField()),
                ('phone_check', models.BooleanField(default=False)),
                ('tracking_date', models.DateField()),
                ('tiktok_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_numbers', to='myapp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
