# Generated by Django 5.2.3 on 2025-07-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatracking',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/data_tracking/'),
        ),
        migrations.AddField(
            model_name='kol',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/kols/'),
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/tracking/'),
        ),
    ]
