# Generated by Django 5.2.3 on 2025-08-26 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('clicks_today', models.IntegerField(default=0)),
                ('orders_today', models.IntegerField(default=0)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('tiktok_url', models.URLField()),
                ('avatar', models.URLField(blank=True, null=True)),
                ('categories', models.JSONField(default=list)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True)),
                ('followers_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-followers_count'],
            },
        ),
        migrations.CreateModel(
            name='CreatorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('products_sold', models.IntegerField(default=0)),
                ('gpm', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_gmv_per_customer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_products', models.IntegerField(default=0)),
                ('price_range_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_range_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('brands_collaborated', models.IntegerField(default=0)),
                ('live_gmv_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('video_gmv_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product_card_gmv_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category_performance', models.JSONField(default=dict)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='myapp.creator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowerDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('female_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_18_24_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_25_34_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_35_44_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_45_54_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_55_plus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('top_locations', models.JSONField(default=list)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_demographics', to='myapp.creator')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='LiveAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_live_sessions', models.IntegerField(default=0)),
                ('average_viewers', models.BigIntegerField(default=0)),
                ('average_engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpm_live', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_analytics', to='myapp.creator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos', models.IntegerField(default=0)),
                ('average_views', models.BigIntegerField(default=0)),
                ('average_engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpm_video', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analytics', to='myapp.creator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('products_sold', models.IntegerField(default=0)),
                ('followers_gained', models.IntegerField(default=0)),
                ('video_views', models.BigIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_data', to='myapp.creator')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('creator', 'date')},
            },
        ),
    ]
